name: showy
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  kartal: ^3.2.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/